List skills = [
  {'id': 0, 'title': 'HTML', 'logo': 'skills_icons/html80.png'},
  {'id': 1, 'title': 'CSS', 'logo': 'skills_icons/css80.png'},
  {'id': 2, 'title': 'JavaScript', 'logo': 'skills_icons/javascript80.png'},
  {'id': 3, 'title': 'React', 'logo': 'skills_icons/react80.png'},
  {'id': 4, 'title': 'jQuery', 'logo': 'skills_icons/jquery80.png'},
  {'id': 5, 'title': 'Pug', 'logo': 'skills_icons/pugtrans80.png'},
  {'id': 6, 'title': 'Node.js', 'logo': 'skills_icons/nodejs80.png'},
  {'id': 7, 'title': 'Express.js', 'logo': 'skills_icons/express80.png'},
  {'id': 8, 'title': 'REST API', 'logo': 'skills_icons/restapi80.png'},
  {'id': 9, 'title': 'Dart', 'logo': 'skills_icons/dart80.png'},
  {'id': 10, 'title': 'Flutter', 'logo': 'skills_icons/flutter80.png'},
  {'id': 11, 'title': 'MongoDB', 'logo': 'skills_icons/mongodb80.png'},
  {'id': 12, 'title': 'Mongoose', 'logo': 'skills_icons/mongoose76.png'},
  {'id': 13, 'title': 'Firebase', 'logo': 'skills_icons/firebase80.png'},
  {'id': 14, 'title': 'MySQL', 'logo': 'skills_icons/mysql80.png'},
  {'id': 15, 'title': 'GitHub', 'logo': 'skills_icons/github80.png'},
  {'id': 16, 'title': 'VS Code ', 'logo': 'skills_icons/vscode80.png'},
  {
    'id': 17,
    'title': 'Android Studio',
    'logo': 'skills_icons/androidstudio80.png'
  },
  {'id': 18, 'title': 'Command Line', 'logo': 'skills_icons/commandline80.png'},
  {'id': 19, 'title': 'NPM', 'logo': 'skills_icons/npm80.png'},
  {'id': 20, 'title': 'JSON', 'logo': 'skills_icons/json80.png'},
];
